config/routes.rb
ParkBench::Application.routes.draw do
  devise_for :users
  get '/facts' => 'number_facts#search', :as => :number_facts
  root to: 'number_facts#index'
end

app/models/number_api.rb
class NumberAPI
  API_END_POINT = 'https://numbersapi.p.mashape.com/%s/%s?fragment=true&json=true&notfound=floor'
  API_KEY = 'ntVAcevJaKmshB9gmiWkMcoAtllnp1hdriNjsnMSLxKwBltzA0'
  # type of numbers
  NUMBER_TYPES = %w{math trivia year}

  def self.get_number_facts(number = 0)
    Rails.cache.fetch("number-api-#{number}", expires_in: 12.hours) do
      facts = []
      # call API multiple times to get more results, API it self only return 1 result against a single call
      4.times do
        NUMBER_TYPES.each do |type|
          response = Unirest.get(API_END_POINT % [number, type], headers:{ "X-Mashape-Key" => API_KEY, "Accept" => "text/plain" })
          facts << response.body['text']
        end
      end
      facts.uniq!
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/number_facts_controller.rb
class NumberFactsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def search
    # number against which we need to fetch results
    @number  = params[:number].to_i
    begin
      facts = NumberAPI.get_number_facts(@number)
      current_page = (params[:page] || 1).to_i
      @facts = facts.paginate(:page => current_page, :per_page => 5)
    rescue
      @facts = [].paginate(:page => 1, :per_page => 5)
    end
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright <%= Time.now.year %> Bilal Naeem</p>
      </div>
    </div>
  </div>
</footer>
<%= render 'shared/ajax_loader' %>

app/views/layouts/_header.html.erb
<div class="contain-to-grid">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Number Facts", root_path %></a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="right">
        <% if user_signed_in? %>
          <li class="divider"></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'button alert') %></li>
        <% else %>
          <li class="divider"></li>
          <li>
            <%- if controller_name != 'sessions' %>
              <%= link_to "Log in", new_session_path(:user), class: 'button' %>
            <% end -%>
          </li>

          <li>
            <%- if controller_name != 'registrations' %>
              <%= link_to "Sign up", new_registration_path(:user), class: 'button success' %>
            <% end -%>
          </li>
        <% end %>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title><%= content_for?(:title) ? yield(:title) + ' | Number Facts' : 'Number Facts' %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-54c0ca1d1e869471" async="async"></script>
<%= render 'layouts/header' %>

<div class="row">
  <div class="large-12 columns"><%= yield %></div>
</div>

<%= render 'layouts/footer' %>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/number_facts/_fact_list.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="panel">
      <h1>Facts for number <%= number %></h1>
    </div>
  </div>
</div>

<div class="row">
  <!-- Main Feed -->
  <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
  <div class="large-12 columns">
    <% if facts.length > 1 %>
        <% facts.each do |fact| %>
        <!-- Start Number Fact -->
        <div class="row">
          <div class="large-12 columns">
            <p><%= fact.capitalize %>.</p>
          </div>
        </div>
        <!-- End Number Fact -->
        <% end %>
    <% else %>
        <div class="row">
          <div class="large-12 columns">
            <h3>No facts found please try again some other number.</h3>
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="panel">
  <%= will_paginate facts %>
</div>

app/views/number_facts/index.html.erb
<% title 'Get to know numbers more'  %>
<h1>Enter a number or year to get facts</h1>

<%= form_tag(number_facts_path, remote: true, format: :json, method: :get) do %>

    <div class="field">
      <%= text_field_tag :number %>
    </div>
    <div class="actions">
      <%= submit_tag 'Get random facts' %>
    </div>
<% end %>

<div class="fact-grid" id="fact_grid">

</div>

app/views/number_facts/search.js.erb
$("#fact_grid").html("<%= escape_javascript(render partial: 'fact_list', locals: { facts: @facts, number: @number } ) %>");
$('.pagination a').attr('data-remote', 'true');

app/views/shared/_ajax_loader.html.erb
<div class="ajax-loader">
  <%= image_tag(asset_url('ajax_loader.gif'), :height => '64', :width => '64') %>
  <br>Loading..
</div>